// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: btdaemon.proto

package btdaemons

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsReadyRequest) Reset() {
	*x = IsReadyRequest{}
	mi := &file_btdaemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReadyRequest) ProtoMessage() {}

func (x *IsReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReadyRequest.ProtoReflect.Descriptor instead.
func (*IsReadyRequest) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{0}
}

type IsReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsReadyResponse) Reset() {
	*x = IsReadyResponse{}
	mi := &file_btdaemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReadyResponse) ProtoMessage() {}

func (x *IsReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReadyResponse.ProtoReflect.Descriptor instead.
func (*IsReadyResponse) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{1}
}

func (x *IsReadyResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type ConnectBleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectBleRequest) Reset() {
	*x = ConnectBleRequest{}
	mi := &file_btdaemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectBleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectBleRequest) ProtoMessage() {}

func (x *ConnectBleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectBleRequest.ProtoReflect.Descriptor instead.
func (*ConnectBleRequest) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectBleRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ConnectBleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectBleResponse) Reset() {
	*x = ConnectBleResponse{}
	mi := &file_btdaemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectBleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectBleResponse) ProtoMessage() {}

func (x *ConnectBleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectBleResponse.ProtoReflect.Descriptor instead.
func (*ConnectBleResponse) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectBleResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type DisconnectBleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectBleRequest) Reset() {
	*x = DisconnectBleRequest{}
	mi := &file_btdaemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectBleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectBleRequest) ProtoMessage() {}

func (x *DisconnectBleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectBleRequest.ProtoReflect.Descriptor instead.
func (*DisconnectBleRequest) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{4}
}

func (x *DisconnectBleRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type DisconnectBleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectBleResponse) Reset() {
	*x = DisconnectBleResponse{}
	mi := &file_btdaemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectBleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectBleResponse) ProtoMessage() {}

func (x *DisconnectBleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectBleResponse.ProtoReflect.Descriptor instead.
func (*DisconnectBleResponse) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{5}
}

type ReadCharRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId     string                 `protobuf:"bytes,1,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	CharacteristicId string                 `protobuf:"bytes,2,opt,name=characteristicId,proto3" json:"characteristicId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadCharRequest) Reset() {
	*x = ReadCharRequest{}
	mi := &file_btdaemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCharRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCharRequest) ProtoMessage() {}

func (x *ReadCharRequest) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCharRequest.ProtoReflect.Descriptor instead.
func (*ReadCharRequest) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{6}
}

func (x *ReadCharRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ReadCharRequest) GetCharacteristicId() string {
	if x != nil {
		return x.CharacteristicId
	}
	return ""
}

type ReadCharResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []byte                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCharResponse) Reset() {
	*x = ReadCharResponse{}
	mi := &file_btdaemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCharResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCharResponse) ProtoMessage() {}

func (x *ReadCharResponse) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCharResponse.ProtoReflect.Descriptor instead.
func (*ReadCharResponse) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{7}
}

func (x *ReadCharResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type WriteCharRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId     string                 `protobuf:"bytes,1,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	CharacteristicId string                 `protobuf:"bytes,2,opt,name=characteristicId,proto3" json:"characteristicId,omitempty"`
	WithResponse     bool                   `protobuf:"varint,3,opt,name=withResponse,proto3" json:"withResponse,omitempty"`
	Data             []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteCharRequest) Reset() {
	*x = WriteCharRequest{}
	mi := &file_btdaemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCharRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCharRequest) ProtoMessage() {}

func (x *WriteCharRequest) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCharRequest.ProtoReflect.Descriptor instead.
func (*WriteCharRequest) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{8}
}

func (x *WriteCharRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *WriteCharRequest) GetCharacteristicId() string {
	if x != nil {
		return x.CharacteristicId
	}
	return ""
}

func (x *WriteCharRequest) GetWithResponse() bool {
	if x != nil {
		return x.WithResponse
	}
	return false
}

func (x *WriteCharRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteCharResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []byte                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCharResponse) Reset() {
	*x = WriteCharResponse{}
	mi := &file_btdaemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCharResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCharResponse) ProtoMessage() {}

func (x *WriteCharResponse) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCharResponse.ProtoReflect.Descriptor instead.
func (*WriteCharResponse) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{9}
}

func (x *WriteCharResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type NotifyCharRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId     string                 `protobuf:"bytes,1,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	CharacteristicId string                 `protobuf:"bytes,2,opt,name=characteristicId,proto3" json:"characteristicId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotifyCharRequest) Reset() {
	*x = NotifyCharRequest{}
	mi := &file_btdaemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyCharRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyCharRequest) ProtoMessage() {}

func (x *NotifyCharRequest) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyCharRequest.ProtoReflect.Descriptor instead.
func (*NotifyCharRequest) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{10}
}

func (x *NotifyCharRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *NotifyCharRequest) GetCharacteristicId() string {
	if x != nil {
		return x.CharacteristicId
	}
	return ""
}

type NotifyCharResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []byte                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyCharResponse) Reset() {
	*x = NotifyCharResponse{}
	mi := &file_btdaemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyCharResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyCharResponse) ProtoMessage() {}

func (x *NotifyCharResponse) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyCharResponse.ProtoReflect.Descriptor instead.
func (*NotifyCharResponse) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{11}
}

func (x *NotifyCharResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_btdaemon_proto protoreflect.FileDescriptor

const file_btdaemon_proto_rawDesc = "" +
	"\n" +
	"\x0ebtdaemon.proto\x12\tbtdaemons\"\x10\n" +
	"\x0eIsReadyRequest\")\n" +
	"\x0fIsReadyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"'\n" +
	"\x11ConnectBleRequest\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"8\n" +
	"\x12ConnectBleResponse\x12\"\n" +
	"\fconnectionId\x18\x01 \x01(\tR\fconnectionId\":\n" +
	"\x14DisconnectBleRequest\x12\"\n" +
	"\fconnectionId\x18\x01 \x01(\tR\fconnectionId\"\x17\n" +
	"\x15DisconnectBleResponse\"a\n" +
	"\x0fReadCharRequest\x12\"\n" +
	"\fconnectionId\x18\x01 \x01(\tR\fconnectionId\x12*\n" +
	"\x10characteristicId\x18\x02 \x01(\tR\x10characteristicId\".\n" +
	"\x10ReadCharResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\"\x9a\x01\n" +
	"\x10WriteCharRequest\x12\"\n" +
	"\fconnectionId\x18\x01 \x01(\tR\fconnectionId\x12*\n" +
	"\x10characteristicId\x18\x02 \x01(\tR\x10characteristicId\x12\"\n" +
	"\fwithResponse\x18\x03 \x01(\bR\fwithResponse\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"/\n" +
	"\x11WriteCharResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\"c\n" +
	"\x11NotifyCharRequest\x12\"\n" +
	"\fconnectionId\x18\x01 \x01(\tR\fconnectionId\x12*\n" +
	"\x10characteristicId\x18\x02 \x01(\tR\x10characteristicId\"0\n" +
	"\x12NotifyCharResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse2\xcf\x03\n" +
	"\x06Daemon\x12B\n" +
	"\aIsReady\x12\x19.btdaemons.IsReadyRequest\x1a\x1a.btdaemons.IsReadyResponse\"\x00\x12K\n" +
	"\n" +
	"ConnectBle\x12\x1c.btdaemons.ConnectBleRequest\x1a\x1d.btdaemons.ConnectBleResponse\"\x00\x12T\n" +
	"\rDisconnectBle\x12\x1f.btdaemons.DisconnectBleRequest\x1a .btdaemons.DisconnectBleResponse\"\x00\x12E\n" +
	"\bReadChar\x12\x1a.btdaemons.ReadCharRequest\x1a\x1b.btdaemons.ReadCharResponse\"\x00\x12H\n" +
	"\tWriteChar\x12\x1b.btdaemons.WriteCharRequest\x1a\x1c.btdaemons.WriteCharResponse\"\x00\x12M\n" +
	"\n" +
	"NotifyChar\x12\x1c.btdaemons.NotifyCharRequest\x1a\x1d.btdaemons.NotifyCharResponse\"\x000\x01B7Z5github.com/Sighery/turnkey/daemons/protogen/btdaemonsb\x06proto3"

var (
	file_btdaemon_proto_rawDescOnce sync.Once
	file_btdaemon_proto_rawDescData []byte
)

func file_btdaemon_proto_rawDescGZIP() []byte {
	file_btdaemon_proto_rawDescOnce.Do(func() {
		file_btdaemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_btdaemon_proto_rawDesc), len(file_btdaemon_proto_rawDesc)))
	})
	return file_btdaemon_proto_rawDescData
}

var file_btdaemon_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_btdaemon_proto_goTypes = []any{
	(*IsReadyRequest)(nil),        // 0: btdaemons.IsReadyRequest
	(*IsReadyResponse)(nil),       // 1: btdaemons.IsReadyResponse
	(*ConnectBleRequest)(nil),     // 2: btdaemons.ConnectBleRequest
	(*ConnectBleResponse)(nil),    // 3: btdaemons.ConnectBleResponse
	(*DisconnectBleRequest)(nil),  // 4: btdaemons.DisconnectBleRequest
	(*DisconnectBleResponse)(nil), // 5: btdaemons.DisconnectBleResponse
	(*ReadCharRequest)(nil),       // 6: btdaemons.ReadCharRequest
	(*ReadCharResponse)(nil),      // 7: btdaemons.ReadCharResponse
	(*WriteCharRequest)(nil),      // 8: btdaemons.WriteCharRequest
	(*WriteCharResponse)(nil),     // 9: btdaemons.WriteCharResponse
	(*NotifyCharRequest)(nil),     // 10: btdaemons.NotifyCharRequest
	(*NotifyCharResponse)(nil),    // 11: btdaemons.NotifyCharResponse
}
var file_btdaemon_proto_depIdxs = []int32{
	0,  // 0: btdaemons.Daemon.IsReady:input_type -> btdaemons.IsReadyRequest
	2,  // 1: btdaemons.Daemon.ConnectBle:input_type -> btdaemons.ConnectBleRequest
	4,  // 2: btdaemons.Daemon.DisconnectBle:input_type -> btdaemons.DisconnectBleRequest
	6,  // 3: btdaemons.Daemon.ReadChar:input_type -> btdaemons.ReadCharRequest
	8,  // 4: btdaemons.Daemon.WriteChar:input_type -> btdaemons.WriteCharRequest
	10, // 5: btdaemons.Daemon.NotifyChar:input_type -> btdaemons.NotifyCharRequest
	1,  // 6: btdaemons.Daemon.IsReady:output_type -> btdaemons.IsReadyResponse
	3,  // 7: btdaemons.Daemon.ConnectBle:output_type -> btdaemons.ConnectBleResponse
	5,  // 8: btdaemons.Daemon.DisconnectBle:output_type -> btdaemons.DisconnectBleResponse
	7,  // 9: btdaemons.Daemon.ReadChar:output_type -> btdaemons.ReadCharResponse
	9,  // 10: btdaemons.Daemon.WriteChar:output_type -> btdaemons.WriteCharResponse
	11, // 11: btdaemons.Daemon.NotifyChar:output_type -> btdaemons.NotifyCharResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_btdaemon_proto_init() }
func file_btdaemon_proto_init() {
	if File_btdaemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_btdaemon_proto_rawDesc), len(file_btdaemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_btdaemon_proto_goTypes,
		DependencyIndexes: file_btdaemon_proto_depIdxs,
		MessageInfos:      file_btdaemon_proto_msgTypes,
	}.Build()
	File_btdaemon_proto = out.File
	file_btdaemon_proto_goTypes = nil
	file_btdaemon_proto_depIdxs = nil
}
