// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: btdaemon.proto

package btdaemons

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsReadyRequest) Reset() {
	*x = IsReadyRequest{}
	mi := &file_btdaemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReadyRequest) ProtoMessage() {}

func (x *IsReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReadyRequest.ProtoReflect.Descriptor instead.
func (*IsReadyRequest) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{0}
}

type IsReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsReadyResponse) Reset() {
	*x = IsReadyResponse{}
	mi := &file_btdaemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReadyResponse) ProtoMessage() {}

func (x *IsReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_btdaemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReadyResponse.ProtoReflect.Descriptor instead.
func (*IsReadyResponse) Descriptor() ([]byte, []int) {
	return file_btdaemon_proto_rawDescGZIP(), []int{1}
}

func (x *IsReadyResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_btdaemon_proto protoreflect.FileDescriptor

const file_btdaemon_proto_rawDesc = "" +
	"\n" +
	"\x0ebtdaemon.proto\x12\tbtdaemons\"\x10\n" +
	"\x0eIsReadyRequest\")\n" +
	"\x0fIsReadyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2L\n" +
	"\x06Daemon\x12B\n" +
	"\aIsReady\x12\x19.btdaemons.IsReadyRequest\x1a\x1a.btdaemons.IsReadyResponse\"\x00B7Z5github.com/Sighery/turnkey/daemons/protogen/btdaemonsb\x06proto3"

var (
	file_btdaemon_proto_rawDescOnce sync.Once
	file_btdaemon_proto_rawDescData []byte
)

func file_btdaemon_proto_rawDescGZIP() []byte {
	file_btdaemon_proto_rawDescOnce.Do(func() {
		file_btdaemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_btdaemon_proto_rawDesc), len(file_btdaemon_proto_rawDesc)))
	})
	return file_btdaemon_proto_rawDescData
}

var file_btdaemon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_btdaemon_proto_goTypes = []any{
	(*IsReadyRequest)(nil),  // 0: btdaemons.IsReadyRequest
	(*IsReadyResponse)(nil), // 1: btdaemons.IsReadyResponse
}
var file_btdaemon_proto_depIdxs = []int32{
	0, // 0: btdaemons.Daemon.IsReady:input_type -> btdaemons.IsReadyRequest
	1, // 1: btdaemons.Daemon.IsReady:output_type -> btdaemons.IsReadyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_btdaemon_proto_init() }
func file_btdaemon_proto_init() {
	if File_btdaemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_btdaemon_proto_rawDesc), len(file_btdaemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_btdaemon_proto_goTypes,
		DependencyIndexes: file_btdaemon_proto_depIdxs,
		MessageInfos:      file_btdaemon_proto_msgTypes,
	}.Build()
	File_btdaemon_proto = out.File
	file_btdaemon_proto_goTypes = nil
	file_btdaemon_proto_depIdxs = nil
}
