// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: btdaemon.proto

package btdaemons

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Daemon_IsReady_FullMethodName       = "/btdaemons.Daemon/IsReady"
	Daemon_ConnectBle_FullMethodName    = "/btdaemons.Daemon/ConnectBle"
	Daemon_DisconnectBle_FullMethodName = "/btdaemons.Daemon/DisconnectBle"
	Daemon_ReadChar_FullMethodName      = "/btdaemons.Daemon/ReadChar"
	Daemon_WriteChar_FullMethodName     = "/btdaemons.Daemon/WriteChar"
	Daemon_NotifyChar_FullMethodName    = "/btdaemons.Daemon/NotifyChar"
)

// DaemonClient is the client API for Daemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Daemon service
type DaemonClient interface {
	IsReady(ctx context.Context, in *IsReadyRequest, opts ...grpc.CallOption) (*IsReadyResponse, error)
	ConnectBle(ctx context.Context, in *ConnectBleRequest, opts ...grpc.CallOption) (*ConnectBleResponse, error)
	DisconnectBle(ctx context.Context, in *DisconnectBleRequest, opts ...grpc.CallOption) (*DisconnectBleResponse, error)
	ReadChar(ctx context.Context, in *ReadCharRequest, opts ...grpc.CallOption) (*ReadCharResponse, error)
	WriteChar(ctx context.Context, in *WriteCharRequest, opts ...grpc.CallOption) (*WriteCharResponse, error)
	NotifyChar(ctx context.Context, in *NotifyCharRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyCharResponse], error)
}

type daemonClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonClient(cc grpc.ClientConnInterface) DaemonClient {
	return &daemonClient{cc}
}

func (c *daemonClient) IsReady(ctx context.Context, in *IsReadyRequest, opts ...grpc.CallOption) (*IsReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsReadyResponse)
	err := c.cc.Invoke(ctx, Daemon_IsReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ConnectBle(ctx context.Context, in *ConnectBleRequest, opts ...grpc.CallOption) (*ConnectBleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectBleResponse)
	err := c.cc.Invoke(ctx, Daemon_ConnectBle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) DisconnectBle(ctx context.Context, in *DisconnectBleRequest, opts ...grpc.CallOption) (*DisconnectBleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectBleResponse)
	err := c.cc.Invoke(ctx, Daemon_DisconnectBle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ReadChar(ctx context.Context, in *ReadCharRequest, opts ...grpc.CallOption) (*ReadCharResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadCharResponse)
	err := c.cc.Invoke(ctx, Daemon_ReadChar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) WriteChar(ctx context.Context, in *WriteCharRequest, opts ...grpc.CallOption) (*WriteCharResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteCharResponse)
	err := c.cc.Invoke(ctx, Daemon_WriteChar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) NotifyChar(ctx context.Context, in *NotifyCharRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NotifyCharResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Daemon_ServiceDesc.Streams[0], Daemon_NotifyChar_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NotifyCharRequest, NotifyCharResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Daemon_NotifyCharClient = grpc.ServerStreamingClient[NotifyCharResponse]

// DaemonServer is the server API for Daemon service.
// All implementations must embed UnimplementedDaemonServer
// for forward compatibility.
//
// Daemon service
type DaemonServer interface {
	IsReady(context.Context, *IsReadyRequest) (*IsReadyResponse, error)
	ConnectBle(context.Context, *ConnectBleRequest) (*ConnectBleResponse, error)
	DisconnectBle(context.Context, *DisconnectBleRequest) (*DisconnectBleResponse, error)
	ReadChar(context.Context, *ReadCharRequest) (*ReadCharResponse, error)
	WriteChar(context.Context, *WriteCharRequest) (*WriteCharResponse, error)
	NotifyChar(*NotifyCharRequest, grpc.ServerStreamingServer[NotifyCharResponse]) error
	mustEmbedUnimplementedDaemonServer()
}

// UnimplementedDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServer struct{}

func (UnimplementedDaemonServer) IsReady(context.Context, *IsReadyRequest) (*IsReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReady not implemented")
}
func (UnimplementedDaemonServer) ConnectBle(context.Context, *ConnectBleRequest) (*ConnectBleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectBle not implemented")
}
func (UnimplementedDaemonServer) DisconnectBle(context.Context, *DisconnectBleRequest) (*DisconnectBleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectBle not implemented")
}
func (UnimplementedDaemonServer) ReadChar(context.Context, *ReadCharRequest) (*ReadCharResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadChar not implemented")
}
func (UnimplementedDaemonServer) WriteChar(context.Context, *WriteCharRequest) (*WriteCharResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteChar not implemented")
}
func (UnimplementedDaemonServer) NotifyChar(*NotifyCharRequest, grpc.ServerStreamingServer[NotifyCharResponse]) error {
	return status.Errorf(codes.Unimplemented, "method NotifyChar not implemented")
}
func (UnimplementedDaemonServer) mustEmbedUnimplementedDaemonServer() {}
func (UnimplementedDaemonServer) testEmbeddedByValue()                {}

// UnsafeDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServer will
// result in compilation errors.
type UnsafeDaemonServer interface {
	mustEmbedUnimplementedDaemonServer()
}

func RegisterDaemonServer(s grpc.ServiceRegistrar, srv DaemonServer) {
	// If the following call pancis, it indicates UnimplementedDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Daemon_ServiceDesc, srv)
}

func _Daemon_IsReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).IsReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_IsReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).IsReady(ctx, req.(*IsReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ConnectBle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectBleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ConnectBle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_ConnectBle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ConnectBle(ctx, req.(*ConnectBleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_DisconnectBle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectBleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).DisconnectBle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_DisconnectBle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).DisconnectBle(ctx, req.(*DisconnectBleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ReadChar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCharRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ReadChar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_ReadChar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ReadChar(ctx, req.(*ReadCharRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_WriteChar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteCharRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).WriteChar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Daemon_WriteChar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).WriteChar(ctx, req.(*WriteCharRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_NotifyChar_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NotifyCharRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServer).NotifyChar(m, &grpc.GenericServerStream[NotifyCharRequest, NotifyCharResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Daemon_NotifyCharServer = grpc.ServerStreamingServer[NotifyCharResponse]

// Daemon_ServiceDesc is the grpc.ServiceDesc for Daemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Daemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "btdaemons.Daemon",
	HandlerType: (*DaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReady",
			Handler:    _Daemon_IsReady_Handler,
		},
		{
			MethodName: "ConnectBle",
			Handler:    _Daemon_ConnectBle_Handler,
		},
		{
			MethodName: "DisconnectBle",
			Handler:    _Daemon_DisconnectBle_Handler,
		},
		{
			MethodName: "ReadChar",
			Handler:    _Daemon_ReadChar_Handler,
		},
		{
			MethodName: "WriteChar",
			Handler:    _Daemon_WriteChar_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NotifyChar",
			Handler:       _Daemon_NotifyChar_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "btdaemon.proto",
}
