syntax = "proto3";

option go_package = "github.com/Sighery/turnkey/daemons/protogen/btdaemons";

package btdaemons;

// Daemon service
service Daemon {
	rpc IsReady(IsReadyRequest) returns (IsReadyResponse) {}
	rpc ConnectBle(ConnectBleRequest) returns (ConnectBleResponse) {}
	rpc ReadChar(ReadCharRequest) returns (ReadCharResponse) {}
	rpc WriteChar(WriteCharRequest) returns (WriteCharResponse) {}
	rpc NotifyChar(NotifyCharRequest) returns (stream NotifyCharResponse) {}
}

message IsReadyRequest {}

message IsReadyResponse {
	bool status = 1;
}

message ConnectBleRequest {
	string addr = 1;
}

message ConnectBleResponse {
	string connectionId = 1;
}

message ReadCharRequest {
	string connectionId = 1;
	string characteristicId = 2;
}

message ReadCharResponse {
	bytes response = 1;
}

message WriteCharRequest {
	string connectionId = 1;
	string characteristicId = 2;
	bool withResponse = 3;
	bytes data = 4;
}

message WriteCharResponse {
	bytes response = 1;
}

message NotifyCharRequest {
	string connectionId = 1;
	string characteristicId = 2;
}

message NotifyCharResponse {
	bytes response = 1;
}
